---

kind: pipeline
name: default

steps:
  - name: Lint role
    image: ansible/galaxy:3.1.6
    commands:
      - /var/lib/galaxy/venv/bin/ansible-lint -x 405 .

  - name: Update Ansible-galaxy
    image: ansible/galaxy:3.1.6
    environment:
      GITHUB_TOKEN:
        from_secret: github-token
    commands:
      - /var/lib/galaxy/venv/bin/ansible-galaxy login --github-token=$GITHUB_TOKEN
      - /var/lib/galaxy/venv/bin/ansible-galaxy import $DRONE_REPO_NAMESPACE $DRONE_REPO_NAME
    when:
      event:
        - tag
