---
- name: recollect facts
  setup: ~
  listen: Collect facts

- name: Stop all Humio instances
  service:
    name: "humio@{{ item }}"
    daemon_reload: yes
    enabled: yes
    state: stopped
  loop: "{{ range(0, humio_processes|int)|list }}"
  listen: Restart Humio
  when: humio_upgrade is not defined

- name: Start all Humio instances
  service:
    name: "humio@{{ item }}"
    state: started
  loop: "{{ range(0, humio_processes|int)|list }}"
  listen: Restart Humio
  when: humio_upgrade is not defined

- name:  Restart Humio service
  throttle: "{{ deploy_concurrency | int }}"
  service:
    name: "humio@{{ item }}"
    state: restarted
    daemon_reload: yes
  loop: "{{ range(0, humio_processes|int)|list }}"
  listen: Restart Humio
  when: deploy_concurrency is defined and humio_upgrade is defined and not humio_shutdown

- name:  Stop all Humio instances - upgrade mode
  service:
    name: "humio@{{ item }}"
    state: restarted
    daemon_reload: yes
  loop: "{{ range(0, humio_processes|int)|list }}"
  listen: Restart Humio
  when: humio_upgrade is defined and humio_shutdown

- name:  Started all Humio instances - upgrade mode
  service:
    name: "humio@{{ item }}"
    state: restarted
    daemon_reload: yes
  loop: "{{ range(0, humio_processes|int)|list }}"
  listen: Restart Humio
  when: humio_upgrade is defined and not humio_shutdown