---
- name: recollect facts
  setup: ~
  listen: Collect facts

- name: restart all Humio instanaces
  service:
    name: "humio@{{ item.key }}"
    daemon_reload: yes
    enabled: yes
    state: restarted
  listen: Restart Humio
  with_dict: "{{ ansible_local.cpusockets }}"