---
- name: recollect facts
  setup: ~
  listen: Collect facts

- name: Stop all Humio instances
  service:
    name: "humio@{{ item }}"
    daemon_reload: yes
    enabled: yes
    state: stopped
  loop: "{{ range(0, humio_processes|int)|list }}"
  listen: Restart Humio

- name: Start all Humio instances
  service:
    name: "humio@{{ item }}"
    state: started
  loop: "{{ range(0, humio_processes|int)|list }}"
  listen: Restart Humio
