---
- name: recollect facts
  setup: ~
  listen: Collect facts

- name: Stop all Humio instances
  service:
    name: "humio@{{ item.key }}"
    daemon_reload: yes
    enabled: yes
    state: stopped
  loop: "{{ ansible_local.cpusockets|dict2items }}"
  listen: Restart Humio

- name: Start all Humio instances
  service:
    name: "humio@{{ item.0.key }}"
    state: started
  loop: "{{ ansible_local.cpusockets|dict2items|product(ansible_play_batch)|list }}"
  delegate_to: "{{ item.1 }}"
  run_once: True
  listen: Restart Humio
